# -*- coding: utf-8 -*-
T = [
    "# Numeriranje kartica",
    "(ništa)",
    "+ Pismo",
    "+ Novo",
    "0 = koristi globalnu glasnoću",
    "00:00 do 00:00 znači Cijeli dan",
    "24h zvona (Genie / NewDay / Owl @ 0.05)",
    "Odgoda: 4 dana 11 sati, 4d 11h, 90m, 1h30, 1.5h\nili vremenski trenutak: 18:30, sutra 9:00\nRadi i na ruskom. Pritisnite Enter za dodavanje.",
    "Drugi --- na dnu, koji zatvara ovaj odjeljak od svega što dođe nakon njega.",
    "Vrlo kratki znakovni signal prisiljava izlazni uređaj da otvori i zatvori svoj tok unutar nekoliko milisekundi, a taj prijelaz može odrezati početak i završetak zvuka. Malo tišine prije i poslije zvuka pomiče prijelaz s audiozapisa. Ništa se ne prigušuje i nijedan uzorak se ne mijenja.",
    "Pokazatelji granica AI-ja",
    "Odbrojavanje do ponovnog postavljanja AI granica",
    "Granice korištenja AI-ja (preostala kvota po prozoru)\nKliknite za osvježavanje",
    "Granice korištenja AI-ja (preostala kvota po prozoru)\\nKliknite za osvježavanje",
    "Pristup",
    "Račun",
    "Računi, oznake, pružatelji i obavijesti po granicama",
    "Potvrdite da ste primijetili protekli događaj — crveno upozorenje na protekli događaj nestaje.",
    "Aktivni slojevi",
    "Aktivne fraze",
    "Aktivni raspon",
    "Aktivni prolazni kanali",
    "Dodaj WAV",
    "Dodaj WAV...",
    "Dodaj stranicu 'Pretpostavke' u birač Ctrl+Q koja drži vlastite\nspremljene položaje prozora (S sprema, Del briše, 1-0 primjenjuje)",
    "Dodaj ponavljajući mjerač vremena za rotirajući prozor korištenja.\nSam se ponovno postavlja svaki period, pa vas i dalje obavještava\nkada pada SLJEDEĆE ponovno postavljanje - čak i nakon više dana izvan mreže.",
    "Dodaj vještinu koju ovaj stroj ne može otkriti.\nRučno dodane oznake preživljavaju ponovno pretraživanje.",
    "Dodaj sve predloške",
    "Dodaj događaj",
    "Dodaj mapu",
    "Dodaj mapu...",
    "Dodaj odmah",
    "Dodaj tihe margine kratkim zvukovima",
    "Dodaj zvuk",
    "Agent",
    "Detalji i vrijeme alarma",
    "Zvuk alarma — prvo naznačeni događaji, zatim svaka datoteka u knjižnici",
    "Boja upozorenja",
    "Centriraj\nCentriraj odabrane blokove.",
    "Poravnaj lijevo\nPoravnaj odabrane blokove ulijevo.",
    "Poravnaj desno\nPoravnaj odabrane blokove udesno.",
    "Svi AI računi skriveni (0% korištenja)",
    "Cijeli dan (24/7)",
    "Sve kategorije",
    "Cijeli dan",
    "Svi zvukovi zaustavljeni",
    "Alt+W je obrnuti Ctrl+W: nova točka ide IZNAD retka na kojem se\nnalazite, a postojeći tekst pomiče se prema dolje.\nIste postavke, čuvane zasebno kako bi se dva smjera\nmogla zasebno ugoditi.",
    "Alt+W…",
    "Jantarno upozorenje",
    "Ambijent",
    "Pravilo ambijenta",
    "Analogni sat",
    "Aplikacija postaje vidljiva",
    "Verzija aplikacije (silo {}):\n{}\n\nVerzija datoteke:\n{}",
    "Verzija aplikacije (silo {}):\\n{}\\n\\nVerzija datoteke:\\n{}",
    "Primijeni",
    "Primjenjuj vanjske izmjene datoteka u stvarnom vremenu. Isključeno: mapa se čita samo kada pretvorite ili ponovno pretražite projekt.",
    "Ploča arhive",
    "Auto",
    "Automatsko pojačanje: {v}",
    "Automatski izjednači omogućene zvukove",
    "Automatsko izjednačavanje: {n} promijenjeno",
    "Automatsko nije dostupno za ovu datoteku",
    "Auto — Kompaktno",
    "Auto — Potpuno",
    "Backspace",
    "Sigurnosna kopija DB-a",
    "Sigurnosna kopija nije prošla provjeru i uklonjena je:\n{}",
    "Sigurnosna kopija nije prošla provjeru i uklonjena je:\\n{}",
    "Sigurnosna kopija nije prošla provjeru; prethodna sigurnosna kopija ostaje nepromijenjena:\n{}",
    "Izradi sigurnosnu kopiju baze podataka",
    "Ugraditi trenutni profil u DEFAULT_PROFILE repozitorija?",
    "Uravnoteženo (zadano)",
    "BkUp",
    "Prazni redci koje gumb Redak i razdjelnik alatne trake stavljaju oko ---.\nCtrl+W ih NE čita - ima vlastiti razmak po scenariju u\ndijalogu Ctrl+W..., zato promjena ovdje nije ništa učinila.",
    "Podebljano",
    "Podebljani / normalni redak",
    "Zvuk prekida:",
    "Ugrađeno",
    "Ugrađeni pregled",
    "Kalendar",
    "Nije moguće izraditi sigurnosnu kopiju: trenutno stanje nije spremljeno u bazu podataka.",
    "Znakova po tokenu (način znakova) ili tokena po riječi (način riječi).\nZadano: 4.0 i 1.33",
    "Veličina škrinje",
    "Odaberite iz unaprijed zadanih predložaka rasporeda intervala",
    "Odaberite preglednik slika",
    "Odaberite program…",
    "Odaberite koje stavke gornje trake se pojavljuju u svakom zasebno uredivom rasponu širine.",
    "Očisti moje riječi",
    "Kliknite mjerač vremena da biste ga uredili.\\nBoja pokazuje koliko je blizu.",
    "Klik: odaberi '{}' i prikaži.\\nDesni klik: spremi trenutačni zvuk ovdje.",
    "Boja:",
    "Boja brojača datuma kada je događaj prošao\n(desni klik vraća na zadanu crvenu boju)",
    "Spektar boja za uređene retke.\nAutomatski prati naglasak teme.",
    "Oboji brojač datuma/vremena kada je vrijeme kalendarskog događaja prošlo i nije potvrđeno — tako se propušten događaj ne zaboravlja. Desnim klikom na oznaku datuma brišete oznaku.",
    "Boja se postepeno mijenja iz plave u crvenu kako rok približava.\nIsključeno: uvijek ista boja.",
    "Potpuno sakrij račune s 0% korištenja u oba prozora, 5-satnom i tjednom.\nPojavit će se tek kada stvarno imaju korištenje (> 0%).",
    "Postavite ponašanje pametnog Ctrl+W po scenariju konteksta:\n• Umetanje razdjelnika i grafičke oznake\n• Razmak praznih redaka (globalno ili po scenariju)\n• Radnja pri pritisku na postojeći razdjelnik",
    "Pretvori u Sync-Project",
    "Kopiraj (Ctrl+C)",
    "Kopiraj sliku",
    "Kopiraj sliku\tCtrl+C",
    "Kopiraj putanju slike",
    "Kopiraj Široko u Srednje",
    "Kopiraj dijagnostiku zvuka",
    "Kopiraj odabrani tekst u drugi silo ili u arhivu.\nOdabir ostaje gdje jest - ništa se ne izreže.",
    "Kopirati ove u upravljanu knjižnicu?",
    "Kopiraj ovu sliku u mehanički okvir\tCtrl+C",
    "Kopirajte svoje trenutačne Windows pokazivače U program.\nProgram ih zatim nastavlja koristiti čak i ako kasnije promijenite\nsistemsku shemu. Pritisnite ponovno za novo kopiranje.",
    "Nije moguće reproducirati {name}",
    "Nije moguće obnoviti silo: radni je prostor pun.",
    "Separator brojača",
    "Stvoreno",
    "Karmin crvena",
    "Ctrl+Alt+klik: novo podređeno silo",
    "Ctrl+C: kopiraj sliku • Ctrl+Shift+C: kopiraj putanju",
    "Ctrl+C: kopiraj • Ctrl+Shift+C: kopiraj putanju",
    "Ctrl+E može ostaviti prostor ispod retka na koji se spustite i zatvoriti odjeljak još jednim --- kako bi sljedeća bilješka počela čisto.\nSve nula i isključeno znači da blok završava na grafičkoj oznaci, kao i dosad.",
    "Ctrl+E ne prepisuje samo redak - slaže cijeli blok:\nnaslov, opcionalnu --- crtu, razmak i grafičku oznaku spremnu za unos.",
    "Ctrl+klik srednjom tipkom na redak u uređivaču",
]
