# -*- coding: utf-8 -*-
T = [
    "Ctrl+W umeće razdjelnik i/ili grafičku oznaku, birajući što učiniti prema položaju kursora.\nOve se vrijednosti primjenjuju na svaki scenarij koji ih ne nadjačava.",
    "Ctrl+W…",
    "Ctrl+povuci za pomicanje ovog razmaka. Dvoklik za preimenovanje.",
    "Trenutni uvjet",
    "Trenutni datum i vrijeme\nKliknite za upravljanje mjeračima vremena i ponovnim postavljanjem granica",
    "Trenutno stanje globalnog utišavanja (prebacuje se tipkom ili potvrdnim okvirom)",
    "Trenutno vrijeme (analogni)\\nKliknite za upravljanje Intervalnim obavijestima",
    "Trenutna širina prozora",
    "Ciklus treperenja kursora (ms). 0 = stalno, bez treperenja.\nZadano: 530 na sustavu Windows.",
    "Prilagođeni Problip zvukovi",
    "Prilagođene boje teme (HEX)",
    "Izreži (Ctrl+X)",
    "Naizmjencični kutovi",
    "POSEBEĆEN BACKEND",
    "Dnevno",
    "Datum",
    "Zadano 24h zvonjenje (Genie / NewDay / Owl @ 0.05)",
    "Zadano dodavanje:",
    "Zadane postavke ažurirane",
    "Briši nakon aktiviranja",
    "Briži unaprijed",
    "Briši odabrani tekst",
    "Briši cijeli taj redak",
    "Razvojni alat: zapiši trenutne postavke sučelja, tema, zvukova i pretpostavki\nkao bazni DEFAULT_PROFILE repozitorija (ne uključuje osobne bilješke, tekst i sila).",
    "Dijalog se otvara",
    "Digitalni datum i vrijeme",
    "Razdjelna crta",
    "Želite li izbrisati SAVSMEĆE iz smeća?\n\nDa: briše tekst i datoteke.\nNe: briše samo tekst, datoteke ostaju.",
    "Dvokliknite mjerač vremena da biste ga uredili.\nBoja pokazuje koliko je blizu.",
    "Dvoklik: otvori",
    "Dvoklik: otvori u pregledniku",
    "Povucite gumbe gornje trake da biste ih preuredili. Isprekidani okviri su\nfleksibilni razmaci — ispustite gumb s bilo koje strane da biste ga premjestili\nizmeđu zona lijevo / sredina / desno. Gumb ↺ (ili desni klik na\novaj tekst) vraća zadani redoslijed.",
    "Nacrtaj --- crtu neposredno pod naslovom. Isključeno ostavlja naslov sam.",
    "Trajanje:",
    "Dinamički (prilagodi prozoru)",
    "Svaka kartica pokazuje što Ctrl+W radi sa uzorkom bilješke. · označava prazan redak, │ kursor.",
    "Svaki redak bloka postavlja se zasebno. Centrirani naslovi pamte se kroz ponovno učitavanje; ostali se smjerovi primjenjuju dok se zaglavlje piše.\nPrazni razmaci nikada se ne poravnavaju - poravnanje tamo prelilo bi se u ono što sljedeće upisujete.",
    "Stvarna amplituda: ~{pct}%",
    "Stvarna širina alatne trake",
    "Iteklo od početka",
    "Smaragdno zelena",
    "Prazni redci između crte i grafičke oznake - prostor za pisanje. 0 stavlja grafičku oznaku neposredno ispod.",
    "Prazni redci ispod grafičke oznake - prostor za nastavak pisanja bez pomicanja teksta ispod vas.",
    "Uključi/isključi",
    "Uključeno",
    "Stanje motora",
    "Escape / odbaci",
    "Procijenjeni ulazni tokeni za otvoreno silo\n{} znakova, {} riječi\nPonderiranje se podešava u Postavke > Uređivač > Redci",
    "Procijenjeni ulazni tokeni za otvoreno silo\n{} znakova, ~ riječi\nPonderiranje se podešava u Postavke > Uređivač > Redci",
    "Procijenjeni ulazni tokeni za otvoreno silo\n~{} znakova, {} riječi\nPonderiranje se podešava u Postavke > Uređivač > Redci",
    "Događaj",
    "Naziv događaja",
    "Vrijeme događaja je u prošlosti; odaberite buduće vrijeme ili onemogućite događaj.",
    "Vrijeme događaja je u prošlosti; odaberite buduće vrijeme da biste ga omogućili.",
    "Događaji",
    "Svaki",
    "Red čekanja svakog sila u ovoj kategoriji. Silo iz kojeg je došao\nsvaki prompt naveden je lijevo.",
    "Svaki zvuk koji aplikacija proizvodi. Promjene se odmah primjenjuju; odabir zvuka ga reproducira. Glasnoća 0 znači \"koristi globalnu glasnoću\".",
    "Sve je vraćeno nazad, a kopija u smeću je sačuvana kako biste mogli pokušati ponovno.",
    "Točno na početku sata / granici sata (:00)",
    "Izuzmi nazive/uzorke:",
    "Izlazak",
    "Izlazak iz FastPromptera",
    "Izlazak iz FastPromptera (Ctrl+Alt+Shift+Q)\nSpremi sve podatke i zatvori aplikaciju.",
    "Izlazak iz FastPromptera (Ctrl+Alt+Shift+Q)\\nSpremi sve podatke i zatvori aplikaciju.",
    "Izvezi Silo u datoteku",
    "Izvezi sve datoteke u ZIP…",
    "Izvoz otkazan",
    "Izvoz nije uspio",
    "Izvezi pretpostavku",
    "Izvezi silo",
    "Izvoz bi preobradio sam sebe na:\n{}",
    "Izvoz bi preobradio sam sebe na:\\n{}",
    "Izvoz u tijeku",
    "Postupno pojačaj",
    "Postupno utišaj",
    "Označi ovaj zvuk kao omiljeni",
    "Datoteka",
    "Ekstenzije datoteka koje se tretiraju kao tekst, odvojene razmacima ili zarezima",
    "Datoteka više ne postoji",
    "Veće datoteke se ne sinkroniziraju",
    "Gumbi filtra (npr. sat, datum, format)...",
    "Filtriraj događaje…",
    "Pronađi",
    "Pokreni ove postavke za 5 sekundi kako biste mogli provjeriti zvuk\ni skočni prozor. Ništa se ne sprema.",
    "Fleksibilni razmak — ispustite gumbe s bilo koje strane da promijenite zonu u kojoj se nalaze",
    "Način fokusa",
    "Mapa",
    "Pismo:",
    "Zaboravi sve riječi koje ste dodali u rječnik",
    "Zaboravi sve riječi koje ste dodali u rječnik?",
    "Format:",
    "Oblikovanje",
    "Od",
    "Od:",
    "Pojačanje",
    "Pojačanje: {gain}",
    "Naziv razmaka",
    "Globalno: {pct}%",
    "Globalna glasnoća: {pct}% - 0 dB = isto kao globalno",
    "Globalno: {pct}%",
    "Uvoz iz GoldSrc / AMX",
    "Zlatno žuta",
    "Format zaglavlja",
    "Zaglavlje+Podebljano+Podcrtano+Žig s vremenom",
    "Sakrij",
    "Sakrij račune s 0% korištenja",
    "Sakrij račune s 0% korištenja (5h i tjedno)",
    "Sakrij dodatne stavke izvan aktivnog raspona",
    "Viši prioritet preživljava dulje kada Auto stavke ne stanu.",
    "Viši prioritet preživljava dulje kada je prostor ograničen",
    "Satno zvono (24/7 @ 0.05)",
    "Satno zvono (24/7)",
    "Kartica na pokazivaču se pojavljuje",
    "Kako Ctrl+E prepisuje redak na kojem se pritisne.\n{text} su vlastite riječi retka, {time} žig, {state}\nriječ za doba dana. Sve ostalo ostaje točno kako je upisano.",
    "Kako se ponderira procjena: znakova po tokenu,\niliti tokena po riječi",
    "Preglednik slika\nKoji program otvara slike s poveznica i iz silo datoteka:\nzadani Windows program, program koji odaberete ili ugrađeni pregled.",
    "Slika se nije mogla prikazati\n{}",
    "Slika se nije mogla prikazati\\n{}",
    "Pregled slike",
]
