"""Shipped defaults — the baked "current configuration" (T-695, T-696).

Generated once from a live profile and then hand-maintained; regenerate with
`scratch/gen_default_profile.py` if the shipped look is ever re-frozen.

This map is merged into `FastPrompterState.reset_data()`, which means it is
BOTH the fresh-install configuration and the fallback an existing database
falls back to for keys it has never stored. Adding a key here therefore
changes what an upgrading user sees for any setting they never touched --
that is intended (it is what "make the current state the default" means), but
it is the reason no key with user CONTENT in it may ever be added: silos,
timers, window geometry and the editor text are excluded on purpose.
"""

DEFAULT_PROFILE = {
    'altw_blanks_after': '1',
    'altw_blanks_before': '0',
    'altw_bullet_char': '•',
    'altw_s1_after': '2',
    'altw_s1_before': '2',
    'altw_s1_bullet': 'True',
    'altw_s1_divider': 'False',
    'altw_s2_after': '2',
    'altw_s2_before': '2',
    'altw_s2_bullet': 'True',
    'altw_s2_divider': 'True',
    'altw_s3_after': '1',
    'altw_s3_before': '0',
    'altw_s3_bullet': 'False',
    'altw_s3_divider': 'True',
    'altw_s4_after': '2',
    'altw_s4_before': '2',
    'altw_s4_bullet': 'True',
    'altw_s4_divider': 'False',
    'altw_s5_after': '3',
    'altw_s5_before': '3',
    'altw_s5_bullet': 'True',
    'altw_s5_divider': 'True',
    'altw_s6_action': 'remove',
    'always_on_top': 'False',
    'always_on_top_hotkey': 'Alt+S',
    'always_on_top_hotkey_alt': '',
    'analog_clock': 'True',
    'auto_bullet': 'True',
    'bold_hash_titles': 'True',
    'bullet_double_line': 'True',
    'button_scale': '0.5',
    'close_on_focus_loss': 'True',
    'code_monospace': 'False',
    'ctrl_c_closes': 'False',
    'ctrl_e_align': 'center',
    'ctrl_e_align_bullet': 'left',
    'ctrl_e_align_rule': 'center',
    'ctrl_e_bullet': 'True',
    'ctrl_e_bullet_char': '•',
    'ctrl_e_center': 'True',
    'ctrl_e_format': '{text} ({time})',
    'ctrl_e_gap_after': '1',
    'ctrl_e_gap_below': '1',
    'ctrl_e_gap_bottom': '1',
    'ctrl_e_rule': 'True',
    'ctrl_e_rule_below': 'False',
    'ctrl_e_stamp_every': 'False',
    'ctrlw_blanks_after': '3',
    'ctrlw_blanks_before': '2',
    'ctrlw_bullet_char': '•',
    'ctrlw_s1_after': '2',
    'ctrlw_s1_before': '2',
    'ctrlw_s1_bullet': 'True',
    'ctrlw_s1_divider': 'False',
    'ctrlw_s2_after': '2',
    'ctrlw_s2_before': '2',
    'ctrlw_s2_bullet': 'True',
    'ctrlw_s2_divider': 'True',
    'ctrlw_s3_after': '2',
    'ctrlw_s3_before': '2',
    'ctrlw_s3_bullet': 'False',
    'ctrlw_s3_divider': 'True',
    'ctrlw_s4_after': '3',
    'ctrlw_s4_before': '0',
    'ctrlw_s4_bullet': 'True',
    'ctrlw_s4_divider': 'False',
    'ctrlw_s5_after': '1',
    'ctrlw_s5_before': '0',
    'ctrlw_s5_bullet': 'True',
    'ctrlw_s5_divider': 'False',
    'ctrlw_s6_action': 'remove',
    'ctrlw_split_behavior': 'bullet',
    'cursor_blink_ms': '1000',
    'custom_colors': {'edit_bg': '#2a3330', 'overlay_new': '#6a5555', 'overlay_recent': '#6a5a40', 'overlay_day': '#5a5a30', 'overlay_old': '#40506a'},
    'custom_cursors': 'True',
    'customize_toolbar': 'False',
    'date_ampm': 'False',
    'date_daypart': 'True',
    'date_emoji': 'False',
    'date_seconds': 'True',
    'date_text_month': 'True',
    'divider_lines_after': '2',
    'drop_bot_left': 'files',
    'drop_bot_right': 'files_link',
    'drop_top_left': 'text',
    'drop_top_right': 'editor_link',
    'fancyzones_fast': 'False',
    'fancyzones_fast_idx': '0',
    'fancyzones_layout': 'Presets',
    'file_panel_docked': 'True',
    'file_panel_view': 'Details',
    'files_dock_open': 'False',
    'files_dock_width': '180',
    'font_family': 'Verdana',
    'font_size': 18,
    'global_hotkey': 'Alt+X',
    'global_hotkey_alt': 'F15',
    'header_position': 'top',
    'hide_extra': 'True',
    'hide_on_clickout_hotkey': 'Alt+A',
    'hide_on_clickout_hotkey_alt': '',
    'hide_shortkeys': 'False',
    'hk_bold': 'Ctrl+B',
    'hk_divider': 'Ctrl+W',
    'hk_export_silo': 'Ctrl+Shift+S',
    'hk_find': 'Ctrl+F',
    'hk_focus': 'Ctrl+D',
    'hk_header': 'Ctrl+E',
    'hk_new_snippet': 'Ctrl+N',
    'hk_quit': 'Ctrl+Alt+Shift+Q',
    'hk_replace': 'Ctrl+H',
    'hk_save_snippet': 'Ctrl+S',
    'hk_snap': 'Ctrl+Q',
    'hk_undo': 'Ctrl+Z',
    'hover_line': 'True',
    'hover_line_color': '#0059ff',
    'hover_line_opacity': '5',
    'hr_visual_line': 'True',
    'language': 'EN',
    'line_heat': 'True',
    'line_heat_palette': 'accent',
    'line_heat_strength': '5',
    'line_marks': 'True',
    'live_preview_conceal': 'True',
    'lock_to_cursor': 'False',
    'lock_window_hotkey': 'Alt+E',
    'lock_window_hotkey_alt': '',
    'normal_window': 'False',
    'numbox_tabs': 'True',
    'paste_mode': 'Plain',
    'pie_menu_hotkey': 'Shift+Alt+X',
    'pie_menu_hotkey_alt': 'Shift+F15',
    'portable_backup_enabled': 'True',
    'preview_mode': 'Live Preview',
    'quote_italic': 'True',
    'saved_sidebar_size': '167',
    'search_visible': 'False',
    'settings_width': '426',
    'show_date_rect': 'True',
    'show_line_numbers': 'False',
    'show_titlebar': 'False',
    'show_token_count': 'False',
    'sidebar_right': 'True',
    'silo_0_hotkey': 'Alt+Shift+Numpad1',
    'silo_0_hotkey_alt': '',
    'silo_1_hotkey': 'Alt+Shift+Numpad2',
    'silo_1_hotkey_alt': '',
    'silo_2_hotkey': 'Alt+Shift+Numpad3',
    'silo_2_hotkey_alt': '',
    'silo_3_hotkey': 'Alt+Shift+Numpad4',
    'silo_3_hotkey_alt': '',
    'silo_4_hotkey': 'Alt+Shift+Numpad5',
    'silo_4_hotkey_alt': '',
    'silo_color_box': 'True',
    'silo_gap_height': '12',
    'silo_home': 'True',
    'silo_pinned_gap': 'True',
    'silo_ticks_enabled': 'True',
    'snippet_0_hotkey': 'Ctrl+Shift+Numpad1',
    'snippet_0_hotkey_alt': '',
    'snippet_1_hotkey': 'Ctrl+Shift+Numpad2',
    'snippet_1_hotkey_alt': '',
    'snippet_2_hotkey': 'Ctrl+Shift+Numpad3',
    'snippet_2_hotkey_alt': '',
    'snippet_3_hotkey': 'Ctrl+Shift+Numpad4',
    'snippet_3_hotkey_alt': '',
    'snippet_4_hotkey': 'Ctrl+Shift+Numpad5',
    'snippet_4_hotkey_alt': '',
    'snippet_5_hotkey': 'Ctrl+Shift+Numpad6',
    'snippet_6_hotkey': 'Ctrl+Shift+Numpad7',
    'snippet_7_hotkey': 'Ctrl+Shift+Numpad8',
    'snippet_8_hotkey': 'Ctrl+Shift+Numpad9',
    'snippet_9_hotkey': 'Ctrl+Shift+Numpad0',
    'snippet_arrows': 'False',
    'snippets_hidden': 'True',
    'snippets_visible': 'False',
    'sound_enabled': 'True',
    'sound_typewriter': 'False',
    'sound_ui': 'True',
    'sound_volume': '1',
    'cs_style': 'False',
    'splitter_sizes': '[178, 1257]',
    'splitter_sizes_left': '',
    'splitter_sizes_right': '[0, 466, 163]',
    'splitter_width': '3',
    'sync_mode': 'Off',
    'tab_overflow_mode': 'Shrink',
    'text_align': 'left',
    'theme': 'Golden Default',
    'timer_show_minutes': 'True',
    'toggle_sidebar_hotkey': 'Alt+D',
    'toggle_sidebar_hotkey_alt': '',
    'token_mode': 'chars',
    'token_weight': '4.0',
    'toolbar_hidden': '',
    'toolbar_order': 'btn_settings_toggle,btn_pin_top,btn_line_nums,cat_combo,cat_numbox,btn_new,btn_save,btn_home,btn_end,btn_trash,btn_toggle_search,btn_toggle_snippets,btn_arc_snip,btn_toggle_archive,btn_project_folder,btn_project_run,btn_files,btn_vision,<stretch>,btn_bold,btn_italic,btn_under,btn_strike,btn_header,btn_quote,btn_align_left,btn_align_center,btn_align_right,btn_overflow,btn_clear_fmt,btn_add_line,btn_bullet_toggle,btn_copy,btn_clear,<stretch>,analog_clock,lbl_date,lbl_timer,<sep>,lbl_line_count,lbl_token_count,btn_settings_toggle_right,btn_help',
    'trash_vision': 'False',
    'tray_visible': 'True',
    'two_sided_buttons': 'True',
    'ui_scale': '0.5',
    'window_locked': 'False',
    'window_presets': [{'name': 'Preset 1', 'x': 0.3338541666666667, 'y': 0.31851851851851853, 'w': 0.5, 'h': 0.6287037037037037, 'state': 'normal'}, {'name': 'Preset 2', 'x': 0.3338541666666667, 'y': 0.31851851851851853, 'w': 0.3338541666666667, 'h': 0.6287037037037037, 'state': 'normal'}, {'name': 'Preset 3', 'x': 0.2916666666666667, 'y': 0.0, 'w': 0.4166666666666667, 'h': 1.0, 'state': 'normal'}],
    'window_presets_enabled': 'True',
    'window_presets_capture_state': 'True',
    'word_wrap': 'True',
    'zebra_lines': 'True',
    'zebra_stripes': 'False',
}
