"""Shipped defaults — the baked "current configuration" (T-695, T-696).

Generated once from a live profile (E-1169, scratchpad gen_defaults.py) and
then hand-maintained; regenerate from a live database if the shipped look is
ever re-frozen.

This map is merged into `FastPrompterState.reset_data()`, which means it is
BOTH the fresh-install configuration and the fallback an existing database
falls back to for keys it has never stored. Adding a key here therefore
changes what an upgrading user sees for any setting they never touched --
that is intended (it is what "make the current state the default" means), but
it is the reason no key with user CONTENT in it may ever be added: silos,
timers, window geometry and the editor text are excluded on purpose.
"""

DEFAULT_PROFILE = {
    "altw_blanks_after": '1',
    "altw_blanks_before": '0',
    "altw_bullet_char": '•',
    "altw_s1_after": '2',
    "altw_s1_before": '2',
    "altw_s1_bullet": 'True',
    "altw_s1_divider": 'False',
    "altw_s2_after": '2',
    "altw_s2_before": '2',
    "altw_s2_bullet": 'True',
    "altw_s2_divider": 'True',
    "altw_s3_after": '1',
    "altw_s3_before": '0',
    "altw_s3_bullet": 'False',
    "altw_s3_divider": 'True',
    "altw_s4_after": '2',
    "altw_s4_before": '2',
    "altw_s4_bullet": 'True',
    "altw_s4_divider": 'False',
    "altw_s5_after": '3',
    "altw_s5_before": '3',
    "altw_s5_bullet": 'True',
    "altw_s5_divider": 'True',
    "altw_s6_action": 'remove',
    "always_on_top": 'False',
    "always_on_top_hotkey": 'Alt+S',
    "always_on_top_hotkey_alt": '',
    "analog_clock": 'True',
    "auto_bullet": 'True',
    "bold_hash_titles": 'True',
    "bullet_double_line": 'True',
    "button_scale": '0.5',
    "close_on_focus_loss": 'False',
    "code_monospace": 'False',
    "codex_gauges": 'False',
    "codex_gauges_refresh_sec": 180,
    "cs_style": 'False',
    "ctrl_c_closes": 'False',
    "ctrl_e_align": 'center',
    "ctrl_e_align_bullet": 'left',
    "ctrl_e_align_rule": 'center',
    "ctrl_e_bullet": 'True',
    "ctrl_e_bullet_char": '•',
    "ctrl_e_center": 'True',
    "ctrl_e_format": '{text} ({time})',
    "ctrl_e_gap_after": '1',
    "ctrl_e_gap_below": '1',
    "ctrl_e_gap_bottom": '1',
    "ctrl_e_rule": 'True',
    "ctrl_e_rule_below": 'False',
    "ctrl_e_stamp_every": 'False',
    "ctrlw_blanks_after": '3',
    "ctrlw_blanks_before": '2',
    "ctrlw_bullet_char": '•',
    "ctrlw_s1_after": '2',
    "ctrlw_s1_before": '2',
    "ctrlw_s1_bullet": 'True',
    "ctrlw_s1_divider": 'False',
    "ctrlw_s2_after": '2',
    "ctrlw_s2_before": '2',
    "ctrlw_s2_bullet": 'True',
    "ctrlw_s2_divider": 'True',
    "ctrlw_s3_after": '2',
    "ctrlw_s3_before": '2',
    "ctrlw_s3_bullet": 'False',
    "ctrlw_s3_divider": 'True',
    "ctrlw_s4_after": '3',
    "ctrlw_s4_before": '0',
    "ctrlw_s4_bullet": 'True',
    "ctrlw_s4_divider": 'False',
    "ctrlw_s5_after": '1',
    "ctrlw_s5_before": '0',
    "ctrlw_s5_bullet": 'True',
    "ctrlw_s5_divider": 'False',
    "ctrlw_s6_action": 'remove',
    "ctrlw_split_behavior": 'bullet',
    "cursor_blink_ms": '1000',
    "custom_colors": {
        'edit_bg': '#2a3330',
        'overlay_day': '#5a5a30',
        'overlay_new': '#6a5555',
        'overlay_old': '#40506a',
        'overlay_recent': '#6a5a40'},
    "custom_cursors": 'True',
    "customize_toolbar": 'False',
    "date_ampm": 'False',
    "date_daypart": 'False',
    "date_emoji": 'False',
    "date_seconds": 'True',
    "date_text_month": 'True',
    "divider_lines_after": '2',
    "drop_bot_left": 'files',
    "drop_bot_right": 'files_link',
    "drop_top_left": 'text',
    "drop_top_right": 'editor_link',
    "fancyzones_fast": 'True',
    "fancyzones_fast_idx": '0',
    "fancyzones_layout": 'Presets',
    "file_panel_docked": 'True',
    "file_panel_view": 'Icons',
    "files_dock_open": 'False',
    "files_dock_width": '181',
    "fkey_action": 'projects',
    "font_family": 'Verdana',
    "font_size": 10,
    "global_hotkey": 'Alt+X',
    "global_hotkey_alt": 'F15',
    "header_position": 'top',
    "hide_extra": 'True',
    "hide_on_clickout_hotkey": 'Alt+A',
    "hide_on_clickout_hotkey_alt": '',
    "hide_shortkeys": 'False',
    "hk_bold": 'Ctrl+B',
    "hk_divider": 'Ctrl+W',
    "hk_export_silo": 'Ctrl+Shift+S',
    "hk_find": 'Ctrl+F',
    "hk_focus": 'Ctrl+D',
    "hk_header": 'Ctrl+E',
    "hk_new_snippet": 'Ctrl+N',
    "hk_quit": 'Ctrl+Alt+Shift+Q',
    "hk_replace": 'Ctrl+H',
    "hk_save_snippet": 'Ctrl+S',
    "hk_snap": 'Ctrl+Q',
    "hk_undo": 'Ctrl+Z',
    "hover_line": 'True',
    "hover_line_color": '#0059ff',
    "hover_line_opacity": '5',
    "hr_visual_line": 'True',
    "interval_notifs": [   {   'align_mode': 'clock',
            'all_day': False,
            'enabled': True,
            'end_minute': 779,
            'id': 'interval_default_noon',
            'last_fired': 1788426000.0041661,
            'last_fired_minute': '2026-09-03 12:00',
            'minutes': 60,
            'name': 'Noon (12:00)',
            'show_in_top_bar': False,
            'show_notification': True,
            'sound': 'file:GENIE.wav',
            'start_minute': 720,
            'volume': 0.05},
        {   'align_mode': 'clock',
            'all_day': False,
            'enabled': True,
            'end_minute': 719,
            'id': 'interval_default_morning',
            'last_fired': 1788415200.4190443,
            'last_fired_minute': '2026-09-03 09:00',
            'minutes': 60,
            'name': 'Morning (07:00 - 11:00)',
            'show_in_top_bar': False,
            'show_notification': True,
            'sound': 'file:newday.wav',
            'start_minute': 420,
            'volume': 0.05},
        {   'align_mode': 'clock',
            'all_day': False,
            'enabled': True,
            'end_minute': 1319,
            'id': 'interval_default_day',
            'last_fired': 1788447600.8779685,
            'last_fired_minute': '2026-09-03 18:00',
            'minutes': 60,
            'name': 'Day & Evening (13:00 - 21:00)',
            'show_in_top_bar': False,
            'show_notification': True,
            'sound': 'file:newday.wav',
            'start_minute': 780,
            'volume': 0.05},
        {   'align_mode': 'clock',
            'all_day': False,
            'enabled': True,
            'end_minute': 419,
            'id': 'interval_default_night',
            'last_fired': 1788404400.6868458,
            'last_fired_minute': '2026-09-03 06:00',
            'minutes': 60,
            'name': 'Night (22:00 - 06:00)',
            'show_in_top_bar': False,
            'show_notification': True,
            'sound': 'file:alert_owl2.wav',
            'start_minute': 1320,
            'volume': 0.05}],
    "language": 'EN',
    "last_save_format": 'md',
    "limit_gauges": 'True',
    "limit_gauges_account_order": [],
    "limit_gauges_refresh_sec": 180,
    "line_heat": 'True',
    "line_heat_palette": 'accent',
    "line_heat_strength": '5',
    "line_marks": 'True',
    "live_preview_conceal": 'True',
    "lock_to_cursor": 'False',
    "lock_window_hotkey": 'Alt+E',
    "lock_window_hotkey_alt": '',
    "normal_window": 'False',
    "numbox_btn_size": '22',
    "numbox_per_row": '10',
    "numbox_tabs": 'True',
    "passed_alert_enabled": 'True',
    "passed_event_color": '#e05555',
    "paste_mode": 'Plain',
    "pie_menu_hotkey": 'Shift+Alt+X',
    "pie_menu_hotkey_alt": 'Shift+F15',
    "portable_backup_enabled": 'True',
    "preview_mode": 'Live Preview',
    "productivity_timer": {   'break_seconds': 930,
        'break_sound': 'file:NEWDAY.wav',
        'breaks_enabled': True,
        'completed_cycles': 0,
        'repeat_alarm': True,
        'sound_enabled': True,
        'volume': 0.05,
        'work_seconds': 2730,
        'work_sound': 'file:QUEST.wav'},
    "project_sync": {},
    "project_sync_all": {},
    "project_sync_map": {},
    "project_sync_map_all": {},
    "quote_italic": 'True',
    "saved_sidebar_size": '254',
    "saved_sound_mappings": {   'button_click': 'cs_style/buttonclick.wav',
        'button_release': 'cs_style/buttonclickrelease.wav',
        'click': 'button1.wav',
        'hover': 'cs_style/buttonrollover.wav'},
    "search_visible": 'False',
    "settings_width": '426',
    "show_date_rect": 'True',
    "show_line_numbers": 'False',
    "show_titlebar": 'False',
    "show_token_count": 'False',
    "sidebar_right": 'True',
    "silo_0_hotkey": 'Alt+Shift+Numpad1',
    "silo_0_hotkey_alt": '',
    "silo_1_hotkey": 'Alt+Shift+Numpad2',
    "silo_1_hotkey_alt": '',
    "silo_2_hotkey": 'Alt+Shift+Numpad3',
    "silo_2_hotkey_alt": '',
    "silo_3_hotkey": 'Alt+Shift+Numpad4',
    "silo_3_hotkey_alt": '',
    "silo_4_hotkey": 'Alt+Shift+Numpad5',
    "silo_4_hotkey_alt": '',
    "silo_color_box": 'True',
    "silo_gap_height": '12',
    "silo_home": 'True',
    "silo_links": {},
    "silo_links_all": {},
    "silo_pinned_gap": 'True',
    "silo_ticks_enabled": 'True',
    "snippet_0_hotkey": 'Ctrl+Shift+Numpad1',
    "snippet_0_hotkey_alt": '',
    "snippet_1_hotkey": 'Ctrl+Shift+Numpad2',
    "snippet_1_hotkey_alt": '',
    "snippet_2_hotkey": 'Ctrl+Shift+Numpad3',
    "snippet_2_hotkey_alt": '',
    "snippet_3_hotkey": 'Ctrl+Shift+Numpad4',
    "snippet_3_hotkey_alt": '',
    "snippet_4_hotkey": 'Ctrl+Shift+Numpad5',
    "snippet_4_hotkey_alt": '',
    "snippet_5_hotkey": 'Ctrl+Shift+Numpad6',
    "snippet_6_hotkey": 'Ctrl+Shift+Numpad7',
    "snippet_7_hotkey": 'Ctrl+Shift+Numpad8',
    "snippet_8_hotkey": 'Ctrl+Shift+Numpad9',
    "snippet_9_hotkey": 'Ctrl+Shift+Numpad0',
    "snippet_arrows": 'False',
    "snippets_hidden": 'False',
    "snippets_visible": 'False',
    "sound_events": {   'archive': {'enabled': 'True', 'file': 'button0.wav', 'volume': ''},
        'backspace': {'enabled': 'True', 'file': 'type_key_3.wav', 'volume': ''},
        'backup': {'enabled': 'True', 'file': 'travel.wav', 'volume': ''},
        'bold': {'enabled': 'True', 'file': 'chat_display_text.wav', 'volume': ''},
        'button_click': {'enabled': 'True', 'file': 'cs_style/buttonclick.wav', 'volume': ''},
        'button_release': {'enabled': 'True', 'file': 'cs_style/buttonclickrelease.wav', 'volume': ''},
        'chest_close': {'enabled': 'True', 'file': 'chest_closed.wav', 'volume': ''},
        'chest_open': {'enabled': 'True', 'file': 'chest_open.wav', 'volume': ''},
        'clear': {'enabled': 'True', 'file': 'warp_teleport08.wav', 'volume': ''},
        'click': {'enabled': 'True', 'file': 'button1.wav', 'volume': ''},
        'copy': {'enabled': 'True', 'file': 'recharged.wav', 'volume': ''},
        'cut': {'enabled': 'True', 'file': 'menu_launch_deny1.wav', 'volume': ''},
        'delete': {'enabled': 'True', 'file': 'ui_clear.wav', 'volume': ''},
        'divider': {'enabled': 'True', 'file': 'menu_mnu_next.wav', 'volume': ''},
        'error': {'enabled': 'True', 'file': 'notify_notification_alert.wav', 'volume': ''},
        'escape': {'enabled': 'True', 'file': 'menu_mnu_next.wav', 'volume': ''},
        'export': {'enabled': 'True', 'file': 'ui_save.wav', 'volume': ''},
        'find': {'enabled': 'True', 'file': 'menu_launch_select1.wav', 'volume': ''},
        'focus': {'enabled': 'True', 'file': 'panel_open.wav', 'volume': ''},
        'header': {'enabled': 'True', 'file': 'click_hint.wav', 'volume': ''},
        'help': {'enabled': 'True', 'file': 'notify_notification2.wav', 'volume': ''},
        'hotkey': {'enabled': 'True', 'file': 'menu_mnu_click.wav', 'volume': ''},
        'hover': {'enabled': 'True', 'file': 'cs_style/buttonrollover.wav', 'volume': ''},
        'italic': {'enabled': 'True', 'file': 'click_cornrclk.wav', 'volume': ''},
        'lock': {'enabled': 'True', 'file': 'click_tactile_click.wav', 'volume': ''},
        'new': {'enabled': 'True', 'file': 'ui_new.wav', 'volume': ''},
        'notify': {'enabled': 'True', 'file': 'notify.wav', 'volume': ''},
        'paste': {'enabled': 'True', 'file': 'pop_up_02.wav', 'volume': ''},
        'profile': {'enabled': 'True', 'file': 'panel_open.wav', 'volume': ''},
        'quit': {'enabled': 'True', 'file': 'menu_launch_select1.wav', 'volume': ''},
        'redo': {'enabled': 'True', 'file': 'blip_bruh.wav', 'volume': ''},
        'replace': {'enabled': 'True', 'file': 'menu3.wav', 'volume': ''},
        'reset': {'enabled': 'True', 'file': 'spy_tape_01.wav', 'volume': ''},
        'restore': {'enabled': 'True', 'file': 'hit_mario_stomp.wav', 'volume': ''},
        'save': {'enabled': 'True', 'file': 'ui_save.wav', 'volume': ''},
        'scroll': {'enabled': 'False', 'file': 'click_cornrclk.wav', 'volume': ''},
        'search': {'enabled': 'True', 'file': 'menu_launch_glow1.wav', 'volume': ''},
        'select_all': {'enabled': 'True', 'file': 'reload1.wav', 'volume': ''},
        'settings': {'enabled': 'True', 'file': 'warp_zoom.wav', 'volume': ''},
        'sidebar': {'enabled': 'True', 'file': 'fire.wav', 'volume': ''},
        'silo': {'enabled': 'True', 'file': 'button1.wav', 'volume': ''},
        'snap': {'enabled': 'True', 'file': 'pickup_weapon_02.wav', 'volume': ''},
        'snippet': {'enabled': 'True', 'file': 'click_double.wav', 'volume': ''},
        'snippets_toggle': {'enabled': 'True', 'file': 'menu_mnu_next.wav', 'volume': ''},
        'strike': {'enabled': 'True', 'file': 'click_tmp_1.wav', 'volume': ''},
        'success': {'enabled': 'True', 'file': 'success_powerup.wav', 'volume': ''},
        'tick': {'enabled': 'True', 'file': 'switch01.wav', 'volume': ''},
        'timer': {'enabled': 'True', 'file': 'success_scored.wav', 'volume': ''},
        'timer_start': {'enabled': 'True', 'file': 'tick_stickybomblauncher_det.wav', 'volume': ''},
        'transform': {'enabled': 'True', 'file': 'click_double.wav', 'volume': ''},
        'type': {'enabled': 'True', 'file': 'type_key_1.wav', 'volume': ''},
        'underline': {'enabled': 'True', 'file': 'click_hint.wav', 'volume': ''},
        'undo': {'enabled': 'True', 'file': 'blip_bow.wav', 'volume': ''},
        'untick': {'enabled': 'True', 'file': 'step_stone3.wav', 'volume': ''},
        'zoom_in': {'enabled': 'True', 'file': 'knife_slash1.wav', 'volume': ''},
        'zoom_out': {'enabled': 'True', 'file': 'blip1.wav', 'volume': ''}},
    "sound_quick_bar": [   'file:NEWDAY.wav',
        'file:NEWMONTH.wav',
        'file:NEWWEEK.wav',
        'file:MILITARY.wav',
        'file:OBELISK.wav',
        'file:GENIE.wav',
        'file:PICKUP01.wav',
        'file:FOUNDITYEAH.wav',
        'file:GAZEBO.wav',
        'file:ROGUE.wav'],
    "sound_typewriter": 'False',
    "sound_ui": 'True',
    "sound_volume": '0.12',
    "splitter_sizes": [178, 1257],
    "splitter_sizes_left": [187, 898, 0],
    "splitter_sizes_right": [0, 771, 254],
    "splitter_width": '3',
    "sync_exclude": ('node_modules, .git, .hg, .svn, .idea, .vscode, .vs, __pycache__, .venv, venv, dist, build, out, '
     'target, bin, obj, .next, .nuxt, .gradle, .terraform, .pytest_cache, .mypy_cache, .ruff_cache, '
     '.cache, coverage, .tox, .eggs, site-packages, Pods, vendor, .DS_Store, Thumbs.db, desktop.ini, '
     '*.pyc, *.exe, *.dll, *.so, *.dylib, *.png, *.jpg, *.jpeg, *.gif, *.bmp, *.ico, *.webp, *.mp3, '
     '*.mp4, *.wav, *.zip, *.rar, *.7z, *.tar, *.gz, *.min.js, *.min.css, *.map, *.woff, *.woff2, '
     '*.ttf, *.otf, *.pdf, *.doc, *.docx, *.xls, *.xlsx, *.ppt, *.pptx'),
    "sync_include": ('.txt .md .markdown .rst .py .pyw .js .mjs .cjs .ts .jsx .tsx .json .yaml .yml .toml .ini .cfg '
     '.conf .csv .tsv .html .htm .css .scss .less .xml .svg .log .sh .bash .zsh .bat .cmd .ps1 .sql .r '
     '.rb .go .rs .java .kt .kts .c .h .cpp .hpp .cc .hh .cs .php .swift .lua .pl .pm .vim .env '
     '.properties .gradle .dockerfile .dockerignore .gitignore .editorconfig .makefile'),
    "sync_live_watch": 'True',
    "sync_max_kb": '512',
    "sync_mode": 'Off',
    "sync_recursive": 'True',
    "tab_overflow_mode": 'Shrink',
    "temp_timer_settings": {   'color_mode': 'temperature',
        'delete_after_fire': False,
        'description': '',
        'increment_minutes': 15,
        'name': 'Temp Timer',
        'show_in_top_bar': True,
        'show_notification': True,
        'sound': 'tick',
        'sound_mode': 'single',
        'sound_rules': [],
        'volume': 0.0},
    "text_align": 'left',
    "theme": 'Golden Default',
    "timer_show_minutes": 'True',
    "toggle_files_hotkey": 'Alt+F',
    "toggle_sidebar_hotkey": 'Alt+D',
    "toggle_sidebar_hotkey_alt": '',
    "token_mode": 'chars',
    "token_weight": '4.0',
    "toolbar_hidden": '',
    "toolbar_order": '',
    "trash_vision": 'False',
    "tray_click_activates": 'True',
    "tray_visible": 'True',
    "two_sided_buttons": 'True',
    "typo_check_enabled": 'False',
    "typo_color": '#e05555',
    "typo_user_words": [],
    "ui_scale": '0.50',
    "window_locked": 'False',
    "window_presets": [   {   'font_size': '10',
            'h': 0.6287037037037037,
            'name': 'Preset 4',
            'sidebar': True,
            'state': 'normal',
            'theme': 'Golden Default',
            'toolbar_position': 'top',
            'ui_scale': '0.50',
            'w': 0.5380208333333333,
            'x': 0.365625,
            'y': 0.32037037037037036,
            'zen': False,
            'zen_solo': False},
        {   'h': 0.6287037037037037,
            'name': 'Preset 2',
            'state': 'normal',
            'w': 0.3338541666666667,
            'x': 0.3338541666666667,
            'y': 0.31851851851851853},
        {   'h': 1.0,
            'name': 'Preset 3',
            'state': 'normal',
            'w': 0.4166666666666667,
            'x': 0.2916666666666667,
            'y': 0.0}],
    "window_presets_capture_state": 'True',
    "window_presets_enabled": 'True',
    "word_wrap": 'True',
    "zebra_lines": 'True',
    "zebra_stripes": 'False',
}
