"""Shipped defaults — the baked "current configuration" (T-695, T-696).

Generated once from a live profile (E-1169, scratchpad gen_defaults.py) and
then hand-maintained; regenerate from a live database if the shipped look is
ever re-frozen.

This map is merged into `FastPrompterState.reset_data()`, which means it is
BOTH the fresh-install configuration and the fallback an existing database
falls back to for keys it has never stored. Adding a key here therefore
changes what an upgrading user sees for any setting they never touched --
that is intended (it is what "make the current state the default" means), but
it is the reason no key with user CONTENT in it may ever be added: silos,
timers, window geometry and the editor text are excluded on purpose.
"""

import copy

from fastprompter.core.interval_presets import DAYPART_CHIME_RULES

# The fresh-profile interval default is the canonical 24h Chime preset
# (T-1359) — the same list the timer dialog offers as a preset, imported
# from core so the two can never drift. A private copy, because consumers
# mutate profile values in place after deepcopying the whole map.
_INTERVAL_NOTIFS_DEFAULT = copy.deepcopy(DAYPART_CHIME_RULES)

DEFAULT_PROFILE = {
    "altw_blanks_after": '1',
    "altw_blanks_before": '0',
    "altw_bullet_char": '•',
    "altw_s1_after": '2',
    "altw_s1_before": '2',
    "altw_s1_bullet": 'True',
    "altw_s1_divider": 'False',
    "altw_s2_after": '2',
    "altw_s2_before": '2',
    "altw_s2_bullet": 'True',
    "altw_s2_divider": 'True',
    "altw_s3_after": '1',
    "altw_s3_before": '0',
    "altw_s3_bullet": 'False',
    "altw_s3_divider": 'True',
    "altw_s4_after": '2',
    "altw_s4_before": '2',
    "altw_s4_bullet": 'True',
    "altw_s4_divider": 'False',
    "altw_s5_after": '3',
    "altw_s5_before": '3',
    "altw_s5_bullet": 'True',
    "altw_s5_divider": 'True',
    "altw_s6_action": 'remove',
    "always_on_top": 'False',
    "always_on_top_hotkey": 'Alt+S',
    "always_on_top_hotkey_alt": '',
    "analog_clock": 'True',
    "archive_visible": 'False',
    "audio_device_render": 'True',
    "audio_edge_pad": 'False',
    "audio_global_muted": 'False',
    "audio_render_policy_migrated_v2": 'True',
    "auto_bullet": 'True',
    "bold_hash_titles": 'True',
    "bullet_double_line": 'True',
    "button_scale": '0.5',
    "close_on_focus_loss": 'False',
    "code_auto_gutter": 'False',
    "code_monospace": 'False',
    "codex_gauges": 'False',
    "codex_gauges_refresh_sec": 180,
    "cs_style": 'False',
    "ctrl_c_closes": 'False',
    "ctrl_e_align": 'center',
    "ctrl_e_align_bullet": 'left',
    "ctrl_e_align_rule": 'center',
    "ctrl_e_bullet": 'True',
    "ctrl_e_bullet_char": '•',
    "ctrl_e_center": 'True',
    "ctrl_e_format": '{text} ({time})',
    "ctrl_e_gap_after": '1',
    "ctrl_e_gap_below": '1',
    "ctrl_e_gap_bottom": '1',
    "ctrl_e_rule": 'True',
    "ctrl_e_rule_below": 'False',
    "ctrl_e_stamp_every": 'False',
    "ctrl_e_follow_edit": 'False',
    "ctrlw_blanks_after": '3',
    "ctrlw_blanks_before": '2',
    "ctrlw_bullet_char": '•',
    "ctrlw_s1_after": '2',
    "ctrlw_s1_before": '2',
    "ctrlw_s1_bullet": 'True',
    "ctrlw_s1_divider": 'False',
    "ctrlw_s2_after": '2',
    "ctrlw_s2_before": '2',
    "ctrlw_s2_bullet": 'True',
    "ctrlw_s2_divider": 'True',
    "ctrlw_s3_after": '2',
    "ctrlw_s3_before": '2',
    "ctrlw_s3_bullet": 'False',
    "ctrlw_s3_divider": 'True',
    "ctrlw_s4_after": '3',
    "ctrlw_s4_before": '0',
    "ctrlw_s4_bullet": 'True',
    "ctrlw_s4_divider": 'False',
    "ctrlw_s5_after": '1',
    "ctrlw_s5_before": '0',
    "ctrlw_s5_bullet": 'True',
    "ctrlw_s5_divider": 'False',
    "ctrlw_s6_action": 'remove',
    "ctrlw_split_behavior": 'bullet',
    "cursor_blink_ms": '1000',
    "custom_colors": {   'edit_bg': '#2a3330',
        'overlay_day': '#5a5a30',
        'overlay_new': '#6a5555',
        'overlay_old': '#40506a',
        'overlay_recent': '#6a5a40'},
    "custom_cursors": 'True',
    "customize_toolbar": 'False',
    "date_ampm": 'False',
    "date_daypart": 'False',
    "date_emoji": 'False',
    "date_seconds": 'False',
    "date_text_month": 'False',
    "divider_lines_after": '2',
    "drop_bot_left": 'files',
    "drop_bot_right": 'files_link',
    "drop_top_left": 'text',
    "drop_top_right": 'editor_link',
    "fancyzones_fast": 'True',
    "fancyzones_fast_idx": '0',
    "fancyzones_layout": 'Presets',
    "file_panel_docked": 'True',
    "file_panel_view": 'Chest',
    "files_dock_open": 'False',
    "files_dock_width": '180',
    "fkey_action": 'projects',
    "font_family": 'Verdana',
    "font_size": 10,
    "global_hotkey": 'Alt+X',
    "global_hotkey_alt": 'F15',
    "header_position": 'top',
    "hide_extra": 'True',
    "hide_on_clickout_hotkey": 'Alt+A',
    "hide_on_clickout_hotkey_alt": '',
    "hide_shortkeys": 'False',
    "hk_audio_mute": 'Ctrl+M',
    "hk_bold": 'Ctrl+B',
    "hk_divider": 'Ctrl+W',
    "hk_export_silo": 'Ctrl+Shift+S',
    "hk_find": 'Ctrl+F',
    "hk_focus": 'Ctrl+D',
    "hk_hashtags": 'Alt+Shift+T',
    "hk_header": 'Ctrl+E',
    "hk_italic": 'Ctrl+I',
    "hk_line_nums": 'Alt+Z',
    "hk_new_snippet": 'Ctrl+N',
    "hk_pack_silo": 'Ctrl+Shift+P',
    "hk_quit": 'Ctrl+Alt+Shift+Q',
    "hk_quote": 'Ctrl+Shift+Q',
    "hk_replace": 'Ctrl+H',
    "hk_save_snippet": 'Ctrl+S',
    "hk_settings": 'Alt+`',
    "hk_snap": 'Ctrl+Q',
    "hk_timers": 'Ctrl+Shift+T',
    "hk_underline": 'Ctrl+U',
    "hk_undo": 'Ctrl+Z',
    "hover_line": 'True',
    "hover_line_color": '#0059ff',
    "hover_line_opacity": '5',
    "hr_visual_line": 'True',
    "image_viewer_mode": 'system',
    "image_viewer_path": '',
    "interval_notifs": _INTERVAL_NOTIFS_DEFAULT,
    "language": 'EN',
    "last_save_format": 'md',
    "limit_colors": {'reset_antigravity': '#8e6ae8', 'reset_codex': '#4bc0ff', 'reset_zcode': '#cfcfcf'},
    "limit_freebuff_enabled": 'False',
    "limit_freebuff_state": '',
    "limit_gauges": 'True',
    "limit_gauges_account_labels": {},
    "limit_gauges_account_order": [],
    "limit_gauges_fill": 'remaining',
    "limit_gauges_hidden_accounts": [],
    "limit_gauges_hide_unusable_5h": 'False',
    "limit_gauges_hide_zero_usage": 'False',
    "limit_gauges_refresh_sec": 180,
    "limit_gauges_show_labels": 'True',
    "limit_gauges_style": 'bars',
    "limit_gauges_vendor_tint": 'True',
    "limit_notif_color": '',
    "limit_notif_duration_sec": 8,
    "limit_notif_symbol": '↻',
    "limit_notification_state": {},
    "limit_notifications": {},
    "limit_zcode_config": '',
    "limit_zcode_enabled": 'False',
    "line_heat": 'True',
    "line_heat_palette": 'accent',
    "line_heat_strength": '5',
    "line_marks": 'True',
    "live_preview_conceal": 'True',
    "lock_to_cursor": 'False',
    "lock_window_hotkey": 'Alt+E',
    "lock_window_hotkey_alt": '',
    "new_silo_paste_clipboard": 'True',
    "normal_window": 'False',
    "numbox_btn_size": '22',
    "numbox_per_row": '10',
    "numbox_tabs": 'True',
    "passed_alert_enabled": 'True',
    "passed_event_color": '#e05555',
    "paste_mode": 'Plain',
    "pie_menu_hotkey": 'Shift+Alt+X',
    "pie_menu_hotkey_alt": 'Shift+F15',
    "portable_backup_enabled": 'True',
    "preview_mode": 'Live Preview',
    "productivity_timer": {   'break_seconds': 930,
        'break_sound': 'file:NEWDAY.wav',
        'breaks_enabled': True,
        'completed_cycles': 0,
        'repeat_alarm': True,
        'sound_enabled': True,
        'volume': 0.05,
        'work_seconds': 2730,
        'work_sound': 'file:QUEST.wav'},
    "project_sync": {},
    "project_sync_all": {},
    "project_sync_map": {},
    "project_sync_map_all": {},
    "quote_italic": 'True',
    "saved_sidebar_size": '258',
    "saved_sound_mappings": {   'button_click': 'cs_style/buttonclick.wav',
        'button_release': 'cs_style/buttonclickrelease.wav',
        'click': 'tick_on.wav',
        'hover': 'cs_style/buttonrollover.wav'},
    "search_visible": 'False',
    "settings_width": '426',
    "show_date_rect": 'True',
    "show_line_numbers": 'False',
    "show_titlebar": 'False',
    "show_token_count": 'False',
    "sidebar_right": 'True',
    "silo_0_hotkey": 'Alt+Shift+Numpad1',
    "silo_0_hotkey_alt": '',
    "silo_1_hotkey": 'Alt+Shift+Numpad2',
    "silo_1_hotkey_alt": '',
    "silo_2_hotkey": 'Alt+Shift+Numpad3',
    "silo_2_hotkey_alt": '',
    "silo_3_hotkey": 'Alt+Shift+Numpad4',
    "silo_3_hotkey_alt": '',
    "silo_4_hotkey": 'Alt+Shift+Numpad5',
    "silo_4_hotkey_alt": '',
    "silo_bundle_keep_versions": '5',
    "silo_chest_slots": 'dynamic',
    "silo_color_box": 'True',
    "silo_gap_height": '12',
    "silo_home": 'True',
    "silo_links": {},
    "silo_links_all": {},
    "silo_pinned_gap": 'True',
    "silo_random_color_on_new": 'True',
    "silo_tabs_mode": 'sidebar',
    "silo_ticks_enabled": 'True',
    "snippet_0_hotkey": 'Ctrl+Shift+Numpad1',
    "snippet_0_hotkey_alt": '',
    "snippet_1_hotkey": 'Ctrl+Shift+Numpad2',
    "snippet_1_hotkey_alt": '',
    "snippet_2_hotkey": 'Ctrl+Shift+Numpad3',
    "snippet_2_hotkey_alt": '',
    "snippet_3_hotkey": 'Ctrl+Shift+Numpad4',
    "snippet_3_hotkey_alt": '',
    "snippet_4_hotkey": 'Ctrl+Shift+Numpad5',
    "snippet_4_hotkey_alt": '',
    "snippet_5_hotkey": 'Ctrl+Shift+Numpad6',
    "snippet_6_hotkey": 'Ctrl+Shift+Numpad7',
    "snippet_7_hotkey": 'Ctrl+Shift+Numpad8',
    "snippet_8_hotkey": 'Ctrl+Shift+Numpad9',
    "snippet_9_hotkey": 'Ctrl+Shift+Numpad0',
    "snippet_arrows": 'False',
    "snippets_hidden": 'True',
    "snippets_visible": 'False',
    "sound_events": {   'app_show': {'enabled': 'False', 'file': 'menu1.wav', 'gain_db': '0.0', 'volume': ''},
        'archive': {'enabled': 'True', 'file': 'button0.wav', 'gain_db': '0.0', 'volume': ''},
        'audio_hub_show': {'enabled': 'False', 'file': 'CaseOpen.wav', 'gain_db': '0.0', 'volume': ''},
        'audio_mute_off': {'enabled': 'True', 'file': 'pop_up_02.wav', 'gain_db': '0.0', 'volume': ''},
        'audio_mute_on': {   'enabled': 'True',
                             'file': 'menu_mnu_empt.wav',
                             'gain_db': '-0.1',
                             'volume': ''},
        'backspace': {'enabled': 'True', 'file': 'type_key_3.wav', 'gain_db': '0.0', 'volume': ''},
        'backup': {'enabled': 'True', 'file': 'travel.wav', 'gain_db': '-0.4', 'volume': ''},
        'bold': {'enabled': 'True', 'file': 'chat_display_text.wav', 'gain_db': '-1.5', 'volume': ''},
        'button_click': {   'enabled': 'True',
                            'file': 'cs_style/buttonclick.wav',
                            'gain_db': '0.0',
                            'volume': ''},
        'button_release': {   'enabled': 'True',
                              'file': 'cs_style/buttonclickrelease.wav',
                              'gain_db': '-1.0',
                              'volume': ''},
        'chest_close': {'enabled': 'True', 'file': 'chest_closed.wav', 'gain_db': '-3.0', 'volume': ''},
        'chest_open': {'enabled': 'True', 'file': 'chest_open.wav', 'gain_db': '-4.1', 'volume': ''},
        'clear': {'enabled': 'True', 'file': 'KILLFADE.wav', 'gain_db': '-2.9', 'volume': ''},
        'click': {'enabled': 'True', 'file': 'tick_on.wav', 'gain_db': '0.0', 'volume': ''},
        'copy': {'enabled': 'True', 'file': 'wpn_hudoff.wav', 'gain_db': '-4.0', 'volume': ''},
        'cut': {'enabled': 'True', 'file': 'menu_launch_deny1.wav', 'gain_db': '0.0', 'volume': ''},
        'delete': {'enabled': 'True', 'file': 'fiveseven_clipout.wav', 'gain_db': '0.0', 'volume': ''},
        'delete_forward': {'enabled': 'True', 'file': 'type_key_2.wav', 'gain_db': '0.0', 'volume': ''},
        'delete_selection': {   'enabled': 'True',
                                'file': 'ui_delete.wav',
                                'gain_db': '0.0',
                                'volume': ''},
        'dialog_show': {'enabled': 'False', 'file': 'menu2.wav', 'gain_db': '0.0', 'volume': ''},
        'divider': {'enabled': 'True', 'file': 'menu_mnu_next.wav', 'gain_db': '0.0', 'volume': ''},
        'error': {'enabled': 'True', 'file': 'errror.wav', 'gain_db': '-0.3', 'volume': ''},
        'escape': {'enabled': 'True', 'file': 'menu_mnu_next.wav', 'gain_db': '0.0', 'volume': ''},
        'export': {'enabled': 'True', 'file': 'ui_save.wav', 'gain_db': '0.0', 'volume': ''},
        'find': {'enabled': 'True', 'file': 'menu_launch_upmenu1.wav', 'gain_db': '0.0', 'volume': ''},
        'focus': {'enabled': 'True', 'file': 'panel_open.wav', 'gain_db': '0.0', 'volume': ''},
        'header': {'enabled': 'True', 'file': 'click_hint.wav', 'gain_db': '0.0', 'volume': ''},
        'help': {   'enabled': 'True',
                    'file': 'notify_notification2.wav',
                    'gain_db': '-0.4',
                    'volume': ''},
        'hotkey': {'enabled': 'True', 'file': 'menu_mnu_click.wav', 'gain_db': '0.0', 'volume': ''},
        'hover': {   'enabled': 'True',
                     'file': 'cs_style/buttonrollover.wav',
                     'gain_db': '0.0',
                     'volume': ''},
        'hover_card_show': {   'enabled': 'False',
                               'file': 'click_hint.wav',
                               'gain_db': '0.0',
                               'volume': ''},
        'italic': {'enabled': 'True', 'file': 'click_cornrclk.wav', 'gain_db': '0.0', 'volume': ''},
        'lock': {'enabled': 'True', 'file': 'click_tactile_click.wav', 'gain_db': '0.0', 'volume': ''},
        'new': {'enabled': 'True', 'file': 'ui_new.wav', 'gain_db': '-3.7', 'volume': ''},
        'notification_show': {   'enabled': 'False',
                                 'file': 'chime_bell_ding1.wav',
                                 'gain_db': '0.0',
                                 'volume': ''},
        'notify': {'enabled': 'True', 'file': 'notify.wav', 'gain_db': '-1.0', 'volume': ''},
        'panel_show': {'enabled': 'False', 'file': 'pop_up_02.wav', 'gain_db': '0.0', 'volume': ''},
        'paste': {'enabled': 'True', 'file': 'pickup_grenade_03.wav', 'gain_db': '-1.0', 'volume': ''},
        'profile': {'enabled': 'True', 'file': 'ui_save.wav', 'gain_db': '0.0', 'volume': ''},
        'project': {'enabled': 'True', 'file': 'HORSE09.wav', 'gain_db': '0.0', 'volume': ''},
        'quit': {'enabled': 'True', 'file': 'click_soft.wav', 'gain_db': '0.0', 'volume': ''},
        'redo': {'enabled': 'True', 'file': 'blip_bruh.wav', 'gain_db': '-4.3', 'volume': ''},
        'replace': {'enabled': 'True', 'file': 'menu_launch_deny1.wav', 'gain_db': '0.0', 'volume': ''},
        'reset': {'enabled': 'True', 'file': 'spy_tape_01.wav', 'gain_db': '-0.1', 'volume': ''},
        'restore': {'enabled': 'True', 'file': 'hit_mario_stomp.wav', 'gain_db': '0.0', 'volume': ''},
        'save': {'enabled': 'True', 'file': 'ui_save.wav', 'gain_db': '0.0', 'volume': ''},
        'scroll': {'enabled': 'False', 'file': 'PICKUP04.wav', 'gain_db': '0.0', 'volume': ''},
        'search': {'enabled': 'True', 'file': 'menu_launch_glow1.wav', 'gain_db': '0.0', 'volume': ''},
        'select_all': {'enabled': 'True', 'file': 'wpn_hudon.wav', 'gain_db': '-2.0', 'volume': ''},
        'settings': {'enabled': 'True', 'file': 'zoom.wav', 'gain_db': '0.0', 'volume': ''},
        'settings_show': {'enabled': 'False', 'file': 'panel_open.wav', 'gain_db': '0.0', 'volume': ''},
        'settings_tab': {   'enabled': 'True',
                            'file': 'menu_launch_upmenu1.wav',
                            'gain_db': '0.0',
                            'volume': ''},
        'sidebar': {'enabled': 'True', 'file': 'm3_insertshell.wav', 'gain_db': '-1.0', 'volume': ''},
        'silo': {'enabled': 'True', 'file': 'tick_on.wav', 'gain_db': '0.0', 'volume': ''},
        'snap': {'enabled': 'True', 'file': 'ui_save.wav', 'gain_db': '0.0', 'volume': ''},
        'snippet': {'enabled': 'True', 'file': 'click_double.wav', 'gain_db': '-0.9', 'volume': ''},
        'snippets_toggle': {   'enabled': 'True',
                               'file': 'menu_mnu_next.wav',
                               'gain_db': '0.0',
                               'volume': ''},
        'strike': {'enabled': 'True', 'file': 'click_tmp_1.wav', 'gain_db': '-6.3', 'volume': ''},
        'success': {'enabled': 'True', 'file': 'success_powerup.wav', 'gain_db': '-9.1', 'volume': ''},
        'tick': {'enabled': 'True', 'file': 'mine_deploy.wav', 'gain_db': '-10.0', 'volume': ''},
        'timer': {   'enabled': 'True',
                     'file': 'success_trade_success.wav',
                     'gain_db': '0.0',
                     'volume': ''},
        'timer_start': {   'enabled': 'True',
                           'file': 'tick_stickybomblauncher_det.wav',
                           'gain_db': '-1.5',
                           'volume': ''},
        'transform': {'enabled': 'True', 'file': 'click_double.wav', 'gain_db': '-0.9', 'volume': ''},
        'type': {'enabled': 'True', 'file': 'type_key_1.wav', 'gain_db': '0.0', 'volume': ''},
        'underline': {'enabled': 'True', 'file': 'click_hint.wav', 'gain_db': '0.0', 'volume': ''},
        'undo': {'enabled': 'True', 'file': 'blip_bow.wav', 'gain_db': '-3.3', 'volume': ''},
        'untick': {'enabled': 'True', 'file': 'click_double.wav', 'gain_db': '-0.9', 'volume': ''},
        'watcher': {'enabled': 'True', 'file': 'notify.wav', 'gain_db': '0.0', 'volume': ''},
        'zoom_in': {'enabled': 'True', 'file': 'knife_slash1.wav', 'gain_db': '-1.5', 'volume': ''},
        'zoom_out': {'enabled': 'True', 'file': 'anchor.wav', 'gain_db': '-2.2', 'volume': ''}},
    "sound_gain_schema": '1',
    "sound_hotkey_on_by_default": 'True',
    "sound_quick_bar": [   'file:NEWDAY.wav',
        'file:NEWMONTH.wav',
        'file:NEWWEEK.wav',
        'file:MILITARY.wav',
        'file:OBELISK.wav',
        'file:GENIE.wav',
        'file:PICKUP01.wav',
        'file:FOUNDITYEAH.wav',
        'file:GAZEBO.wav',
        'file:ROGUE.wav'],
    "sound_typewriter": 'True',
    "sound_ui": 'True',
    "sound_volume": '0.09',
    "splitter_sizes": [178, 1257],
    "splitter_sizes_left": [187, 898, 0],
    "splitter_sizes_right": [0, 768, 258],
    "splitter_width": '3',
    "static_cursor": 'False',
    "sync_exclude": ('node_modules, .git, .hg, .svn, .idea, .vscode, .vs, __pycache__, .venv, venv, dist, build, out, '
     'target, bin, obj, .next, .nuxt, .gradle, .terraform, .pytest_cache, .mypy_cache, .ruff_cache, '
     '.cache, coverage, .tox, .eggs, site-packages, Pods, vendor, .DS_Store, Thumbs.db, desktop.ini, '
     '*.pyc, *.exe, *.dll, *.so, *.dylib, *.png, *.jpg, *.jpeg, *.gif, *.bmp, *.ico, *.webp, *.mp3, '
     '*.mp4, *.wav, *.zip, *.rar, *.7z, *.tar, *.gz, *.min.js, *.min.css, *.map, *.woff, *.woff2, '
     '*.ttf, *.otf, *.pdf, *.doc, *.docx, *.xls, *.xlsx, *.ppt, *.pptx'),
    "sync_include": ('.txt .md .markdown .rst .py .pyw .js .mjs .cjs .ts .jsx .tsx .json .yaml .yml .toml .ini .cfg '
     '.conf .csv .tsv .html .htm .css .scss .less .xml .svg .log .sh .bash .zsh .bat .cmd .ps1 .sql .r '
     '.rb .go .rs .java .kt .kts .c .h .cpp .hpp .cc .hh .cs .php .swift .lua .pl .pm .vim .env '
     '.properties .gradle .dockerfile .dockerignore .gitignore .editorconfig .makefile'),
    "sync_live_watch": 'True',
    "sync_max_kb": '512',
    "sync_mode": 'Off',
    "sync_recursive": 'True',
    "tab_overflow_mode": 'Shrink',
    "temp_timer_settings": {   'color_mode': 'temperature',
        'delete_after_fire': False,
        'description': '',
        'increment_minutes': 15,
        'name': 'Temp Timer',
        'show_in_top_bar': True,
        'show_notification': True,
        'sound': 'file:OBELISK.wav',
        'sound_mode': 'single',
        'sound_rules': [],
        'volume': 0.05},
    "text_align": 'left',
    "theme": 'Golden Default',
    "timer_show_minutes": 'True',
    "toggle_files_hotkey": 'Alt+F',
    "toggle_sidebar_hotkey": 'Alt+D',
    "toggle_sidebar_hotkey_alt": '',
    "token_mode": 'chars',
    "token_weight": '4.0',
    "toolbar_hidden": '',
    "toolbar_order": '',
    "toolbar_position": 'top',
    "topbar_visibility": {   'breakpoints': [   {'id': 'ultra', 'max': 599, 'min': 0},
                           {'id': 'narrow', 'max': 899, 'min': 600},
                           {'id': 'medium', 'max': 1279, 'min': 900},
                           {'id': 'wide', 'max': None, 'min': 1280}],
        'items': {   '_counter_sep': {   'medium': 'show',
                                         'narrow': 'show',
                                         'priority': 10,
                                         'ultra': 'show',
                                         'wide': 'show'},
                     'analog_clock': {   'medium': 'show',
                                         'narrow': 'auto',
                                         'priority': 96,
                                         'ultra': 'auto',
                                         'wide': 'show'},
                     'btn_add_line': {   'medium': 'auto',
                                         'narrow': 'auto',
                                         'priority': 26,
                                         'ultra': 'auto',
                                         'wide': 'show'},
                     'btn_align_center': {   'medium': 'auto',
                                             'narrow': 'auto',
                                             'priority': 18,
                                             'ultra': 'auto',
                                             'wide': 'show'},
                     'btn_align_left': {   'medium': 'auto',
                                           'narrow': 'auto',
                                           'priority': 18,
                                           'ultra': 'auto',
                                           'wide': 'show'},
                     'btn_align_right': {   'medium': 'auto',
                                            'narrow': 'auto',
                                            'priority': 18,
                                            'ultra': 'auto',
                                            'wide': 'show'},
                     'btn_arc_snip': {   'medium': 'auto',
                                         'narrow': 'auto',
                                         'priority': 38,
                                         'ultra': 'auto',
                                         'wide': 'show'},
                     'btn_bold': {   'medium': 'auto',
                                     'narrow': 'auto',
                                     'priority': 30,
                                     'ultra': 'auto',
                                     'wide': 'show'},
                     'btn_bullet_toggle': {   'medium': 'auto',
                                              'narrow': 'auto',
                                              'priority': 28,
                                              'ultra': 'auto',
                                              'wide': 'show'},
                     'btn_clear': {   'medium': 'auto',
                                      'narrow': 'auto',
                                      'priority': 25,
                                      'ultra': 'auto',
                                      'wide': 'show'},
                     'btn_clear_fmt': {   'medium': 'auto',
                                          'narrow': 'auto',
                                          'priority': 16,
                                          'ultra': 'auto',
                                          'wide': 'show'},
                     'btn_copy': {   'medium': 'auto',
                                     'narrow': 'auto',
                                     'priority': 32,
                                     'ultra': 'auto',
                                     'wide': 'show'},
                     'btn_end': {   'medium': 'auto',
                                    'narrow': 'auto',
                                    'priority': 35,
                                    'ultra': 'auto',
                                    'wide': 'show'},
                     'btn_files': {   'medium': 'auto',
                                      'narrow': 'auto',
                                      'priority': 50,
                                      'ultra': 'auto',
                                      'wide': 'show'},
                     'btn_header': {   'medium': 'auto',
                                       'narrow': 'auto',
                                       'priority': 34,
                                       'ultra': 'auto',
                                       'wide': 'show'},
                     'btn_help': {   'medium': 'auto',
                                     'narrow': 'auto',
                                     'priority': 44,
                                     'ultra': 'auto',
                                     'wide': 'show'},
                     'btn_home': {   'medium': 'auto',
                                     'narrow': 'auto',
                                     'priority': 35,
                                     'ultra': 'auto',
                                     'wide': 'show'},
                     'btn_italic': {   'medium': 'auto',
                                       'narrow': 'auto',
                                       'priority': 30,
                                       'ultra': 'auto',
                                       'wide': 'show'},
                     'btn_line_nums': {   'medium': 'auto',
                                          'narrow': 'auto',
                                          'priority': 45,
                                          'ultra': 'auto',
                                          'wide': 'show'},
                     'btn_new': {   'medium': 'show',
                                    'narrow': 'show',
                                    'priority': 120,
                                    'ultra': 'show',
                                    'wide': 'show'},
                     'btn_overflow': {   'medium': 'show',
                                         'narrow': 'show',
                                         'priority': 999,
                                         'ultra': 'show',
                                         'wide': 'show'},
                     'btn_pin_top': {   'medium': 'auto',
                                        'narrow': 'auto',
                                        'priority': 55,
                                        'ultra': 'auto',
                                        'wide': 'show'},
                     'btn_project_folder': {   'medium': 'auto',
                                               'narrow': 'auto',
                                               'priority': 52,
                                               'ultra': 'auto',
                                               'wide': 'show'},
                     'btn_project_run': {   'medium': 'auto',
                                            'narrow': 'auto',
                                            'priority': 52,
                                            'ultra': 'auto',
                                            'wide': 'show'},
                     'btn_quote': {   'medium': 'auto',
                                      'narrow': 'auto',
                                      'priority': 28,
                                      'ultra': 'auto',
                                      'wide': 'show'},
                     'btn_save': {   'medium': 'show',
                                     'narrow': 'show',
                                     'priority': 115,
                                     'ultra': 'show',
                                     'wide': 'show'},
                     'btn_settings_toggle': {   'medium': 'show',
                                                'narrow': 'show',
                                                'priority': 1000,
                                                'ultra': 'show',
                                                'wide': 'show'},
                     'btn_settings_toggle_right': {   'medium': 'auto',
                                                      'narrow': 'auto',
                                                      'priority': 60,
                                                      'ultra': 'auto',
                                                      'wide': 'show'},
                     'btn_sidebar_toggle': {   'medium': 'show',
                                               'narrow': 'show',
                                               'priority': 1000,
                                               'ultra': 'show',
                                               'wide': 'show'},
                     'btn_strike': {   'medium': 'auto',
                                       'narrow': 'auto',
                                       'priority': 22,
                                       'ultra': 'auto',
                                       'wide': 'show'},
                     'btn_toggle_archive': {   'medium': 'auto',
                                               'narrow': 'auto',
                                               'priority': 38,
                                               'ultra': 'auto',
                                               'wide': 'show'},
                     'btn_toggle_search': {   'medium': 'auto',
                                              'narrow': 'auto',
                                              'priority': 48,
                                              'ultra': 'auto',
                                              'wide': 'show'},
                     'btn_toggle_snippets': {   'medium': 'auto',
                                                'narrow': 'auto',
                                                'priority': 46,
                                                'ultra': 'auto',
                                                'wide': 'show'},
                     'btn_toolbar_reset': {   'medium': 'show',
                                              'narrow': 'show',
                                              'priority': 1000,
                                              'ultra': 'show',
                                              'wide': 'show'},
                     'btn_trash': {   'medium': 'auto',
                                      'narrow': 'auto',
                                      'priority': 42,
                                      'ultra': 'auto',
                                      'wide': 'show'},
                     'btn_under': {   'medium': 'auto',
                                      'narrow': 'auto',
                                      'priority': 24,
                                      'ultra': 'auto',
                                      'wide': 'show'},
                     'btn_vision': {   'medium': 'auto',
                                       'narrow': 'auto',
                                       'priority': 40,
                                       'ultra': 'auto',
                                       'wide': 'show'},
                     'cat_combo': {   'medium': 'show',
                                      'narrow': 'auto',
                                      'priority': 100,
                                      'ultra': 'auto',
                                      'wide': 'show'},
                     'cat_numbox': {   'medium': 'show',
                                       'narrow': 'auto',
                                       'priority': 100,
                                       'ultra': 'auto',
                                       'wide': 'show'},
                     'lbl_date': {   'detail': {   'medium': 'full',
                                                   'narrow': 'full',
                                                   'ultra': 'compact',
                                                   'wide': 'full'},
                                     'medium': 'show',
                                     'narrow': 'auto',
                                     'priority': 98,
                                     'ultra': 'auto',
                                     'wide': 'show'},
                     'lbl_limit_timer': {   'medium': 'show',
                                            'narrow': 'auto',
                                            'priority': 95,
                                            'ultra': 'auto',
                                            'wide': 'show'},
                     'lbl_line_count': {   'medium': 'show',
                                           'narrow': 'auto',
                                           'priority': 97,
                                           'ultra': 'auto',
                                           'wide': 'show'},
                     'lbl_timer': {   'medium': 'show',
                                      'narrow': 'auto',
                                      'priority': 90,
                                      'ultra': 'auto',
                                      'wide': 'show'},
                     'lbl_token_count': {   'medium': 'auto',
                                            'narrow': 'auto',
                                            'priority': 72,
                                            'ultra': 'auto',
                                            'wide': 'show'},
                     'limit_gauges': {   'medium': 'show',
                                         'narrow': 'auto',
                                         'priority': 94,
                                         'ultra': 'auto',
                                         'wide': 'show'}},
        'version': 1},
    "trash_vision": 'False',
    "tray_click_activates": 'True',
    "tray_visible": 'True',
    "two_sided_buttons": 'True',
    "typo_check_enabled": 'False',
    "typo_color": '#e05555',
    "typo_user_words": [],
    "ui_scale": '0.50',
    "window_locked": 'False',
    "window_presets": [   {   'font_size': '10',
            'h': 0.6287037037037037,
            'name': 'Preset 4',
            'sidebar': True,
            'state': 'normal',
            'theme': 'Golden Default',
            'toolbar_position': 'top',
            'ui_scale': '0.50',
            'w': 0.5380208333333333,
            'x': 0.365625,
            'y': 0.32037037037037036,
            'zen': False,
            'zen_solo': False},
        {   'h': 0.6287037037037037,
            'name': 'Preset 2',
            'state': 'normal',
            'w': 0.3338541666666667,
            'x': 0.3338541666666667,
            'y': 0.31851851851851853},
        {   'h': 1.0,
            'name': 'Preset 3',
            'state': 'normal',
            'w': 0.4166666666666667,
            'x': 0.2916666666666667,
            'y': 0.0}],
    "window_presets_capture_state": 'True',
    "window_presets_enabled": 'True',
    "word_wrap": 'True',
    "zebra_lines": 'True',
    "zebra_stripes": 'False',
}
