"""Release tree inventory: NUL-safe Git status classification (A-I).

The 0.8.68 reconciliation exists because a large accumulated worktree mixed
accepted product work with scratch, runtime and generated paths, and nothing
could say which was which. This tool answers exactly that, read-only:

- every tracked modification, deletion and untracked path is recorded;
- each path is classified A-I per the release-wave contract;
- release-critical untracked paths raise explicit warnings;
- class I (UNKNOWN) never silently becomes release input.

It stages nothing, deletes nothing and writes only its report. `--strict`
exits 1 while any UNKNOWN path remains.
"""

from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
from datetime import UTC, datetime
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUT = REPO_ROOT / "build" / "release_tree_inventory.json"

CLASS_LABELS = {
    "A": "ACCEPTED PRODUCT SOURCE / REPO INFRASTRUCTURE",
    "B": "ACCEPTED TEST / FIXTURE",
    "C": "ACCEPTED SHIPPED RESOURCE",
    "D": "GENERATED BUT REQUIRED SOURCE ARTIFACT",
    "E": "SAIPEN CANONICAL / RELEASE EVIDENCE",
    "F": "BUILD OUTPUT / CACHE",
    "G": "SESSION / RUNTIME STATE",
    "H": "SCRATCH / DIAGNOSTIC / TEMP",
    "I": "UNKNOWN - MUST BE REVIEWED",
}

GENERATED_SOURCE_FILES = (
    "src/fastprompter/core/typecheck_ui_vocab.py",
    "src/fastprompter/core/typecheck_words.py",
)

_ROOT_ACCEPTED = {
    ".gitattributes",
    ".pre-commit-config.yaml",
    "CHANGELOG.md",
    "LICENSE",
    "README.md",
    "README.ded.md",
    "README.ee.md",
    "README.ja.md",
    "GUIDE_DE.md",
    "GUIDE_EN.md",
    "GUIDE_EST.md",
    "GUIDE_JA.md",
    "GUIDE_RU.md",
    "deploy.cmd",
    "deploy.ps1",
    "release.cmd",
}

_ROOT_SCRATCH_NAMES = {
    "all_untranslated_context.json",
    "append_path_tests.py",
    "bump.py",
    "bump_changelog.py",
    "db_dump.json",
    "diff.txt",
    "fail4.txt",
    "fail5.txt",
    "fail6.txt",
    "finish_state.py",
    "full_run_tail.txt",
    "log_ship.py",
    "mark_board.py",
    "original.py",
    "placeholders.json",
    "prune_board.py",
    "rm_converge.py",
    "ruff.json",
    "scratch.py",
    "scratch_keys.json",
    "unique_keys.json",
    "update_state.py",
    "update_state2.py",
    "write_digest.py",
}

#: T-1353 one-off campaign probes. They live under tools/ but import nothing, are
#: imported by nothing, and are superseded by the i18n_* chain, so shipping them
#: as "release tooling" would misdescribe them. Kept on disk for the campaign
#: record (SAIHANDOFF section 3 forbids opportunistic deletion of T-1353
#: material), never release input. Proof in
#: .saipen/evidence/t1370_tool_lifecycle.json.
_OBSOLETE_TOOL_NAMES = {
    "tools/categorize_keys.py",
    "tools/check_hsc.py",
    "tools/check_keys.py",
    "tools/dump_all_context.py",
    "tools/find_hsc.py",
    "tools/find_ru.py",
    "tools/inspect_keys.py",
    "tools/make_overview.py",
    "tools/make_reference.py",
    "tools/split_batches.py",
}

_SCRATCH_PREFIXES = ("fix_", "patch", "sweep_", "smoke_", "lm", "run")
_SCRATCH_SUFFIXES = (".txt", ".log", ".rar", ".7z", ".zip", ".diff")

_RUNTIME_ROOT_NAMES = {"local_data_v15.db"}
_RUNTIME_SUFFIXES = (".db", ".token", ".bak")
_RUNTIME_FILES = {"crash.log", "error.log"}
_RUNTIME_DIRS = ("data/", ".freebuff/", ".workbuddy-ai/", ".saiwork/", ".codenomad/", ".claude/")

_CACHE_DIRS = (
    "build/",
    ".pytest_cache/",
    ".ruff_cache/",
    ".codebase-memory/",
    ".pytest_probe_tmp/",
    "__pycache__/",
)
_CACHE_FILES = {"nuitka-crash-report.xml"}

#: Machine-local SAIPEN in-flight state (T-1241): OS writer locks, the liveness
#: cache, per-operation journals and staged payloads, and the snapshot
#: generations. These live under .saipen/ but carry no canonical truth -- they
#: are process-local, regenerated by the engine, and must never be classified
#: as release evidence, staged, or shipped.
_SAIPEN_MACHINE_LOCAL = (
    ".saipen/locks/",
    ".saipen/cache/",
    ".saipen/recovery/ops/",
    ".saipen/snapshots/",
)


def _first_dir(path: str) -> str:
    return path.split("/", 1)[0] + "/" if "/" in path else ""


def classify(path: str) -> tuple[str, str]:
    """Return (class letter, short rationale) for one repository-relative path."""
    name = path.rsplit("/", 1)[-1]
    if path == "AGENTS.md":
        return "E", "protocol bootstrap document, must be tracked (T-1241 defect 4)"
    if path.startswith(".github/"):
        return "A", "CI release infrastructure"
    if path.startswith(_SAIPEN_MACHINE_LOCAL):
        return "G", "machine-local SAIPEN in-flight state -- never release input (T-1241)"
    if path.startswith(".saipen/") or path.startswith("audit/"):
        return "E", "SAIPEN canonical memory / release evidence"
    if path in _OBSOLETE_TOOL_NAMES:
        return "H", "superseded one-off campaign probe, zero consumers (T-1370)"
    if path in GENERATED_SOURCE_FILES:
        return "D", "generated vocabulary required by tests and release"
    if path.startswith("tools/") or path.startswith("docs/"):
        return "A", "release tooling / repository documentation"
    if path in (".gitignore", ".gitattributes", ".cbmignore", "requirements.txt"):
        return "A", "repository configuration"
    if path.startswith("src/fastprompter/"):
        return "A", "accepted product source / shipped resources"
    if path.startswith("tests/") or path.startswith("tests_smoke/") or path == "conftest.py":
        return "B", "accepted test or fixture"
    if path.startswith("_res/"):
        return "C", "Nuitka-included shipped resource"
    if path.startswith(_CACHE_DIRS) or _first_dir(path) in _CACHE_DIRS or name in _CACHE_FILES:
        return "F", "build output / cache"
    if path.startswith(_RUNTIME_DIRS) or name in _RUNTIME_ROOT_NAMES or name.endswith(_RUNTIME_SUFFIXES):
        return "G", "session / runtime state"
    if path in _ROOT_ACCEPTED:
        return "A", "accepted repository document"
    if "/" not in path:
        if name in _ROOT_SCRATCH_NAMES or name.startswith(_SCRATCH_PREFIXES) or name.endswith(_SCRATCH_SUFFIXES):
            return "H", "scratch / diagnostic / temp"
    return "I", "unknown - review required"


def _parse_porcelain_v2(raw: bytes) -> list[dict]:
    """NUL-safe parse of `git status --porcelain=v2 -z --untracked-files=all`."""
    records: list[dict] = []
    tokens = raw.split(b"\0")
    index = 0
    while index < len(tokens):
        token = tokens[index]
        index += 1
        if not token:
            continue
        text = token.decode("utf-8", errors="replace")
        kind = text[:1]
        if kind == "?":
            records.append({"kind": "untracked", "status": "?", "path": text[2:]})
        elif kind in ("1", "u"):
            parts = text.split(" ", 8)
            if len(parts) < 9:
                continue
            records.append({"kind": "changed", "status": parts[1], "path": parts[8]})
        elif kind == "2":
            parts = text.split(" ", 9)
            if len(parts) < 10:
                continue
            record = {"kind": "renamed", "status": parts[1], "path": parts[9]}
            if index < len(tokens) and tokens[index]:
                record["orig_path"] = tokens[index].decode("utf-8", errors="replace")
                index += 1
            records.append(record)
        elif kind == "!":
            records.append({"kind": "ignored", "status": "!", "path": text[2:]})
        else:
            records.append({"kind": "other", "status": kind, "path": text})
    return records


def _git_status_raw(root: Path) -> bytes:
    proc = subprocess.run(
        ["git", "status", "--porcelain=v2", "-z", "--untracked-files=all"],
        cwd=str(root),
        capture_output=True,
    )
    if proc.returncode != 0:
        raise RuntimeError(
            f"git status failed ({proc.returncode}): "
            f"{proc.stderr.decode('utf-8', errors='replace')[:300]}"
        )
    return proc.stdout


def build_report(root: Path = REPO_ROOT) -> dict:
    records = _parse_porcelain_v2(_git_status_raw(root))
    entries = []
    counts = {letter: 0 for letter in CLASS_LABELS}
    warnings: list[str] = []
    for record in records:
        letter, rationale = classify(record["path"])
        counts[letter] += 1
        entry = {
            "path": record["path"],
            "kind": record["kind"],
            "status": record["status"],
            "class": letter,
            "rationale": rationale,
        }
        if "orig_path" in record:
            entry["orig_path"] = record["orig_path"]
        entries.append(entry)
        if letter in ("A", "B", "C", "D") and record["kind"] == "untracked":
            warnings.append(
                f"release-critical path is UNTRACKED and must be staged explicitly: {record['path']}"
            )
    entries.sort(key=lambda item: (item["class"], item["path"]))
    tracked = sum(1 for record in records if record["kind"] != "untracked")
    unknown = counts["I"]
    return {
        "schema_version": 1,
        "operation": "release_tree_inventory",
        "recorded_at": datetime.now(tz=UTC).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "root": str(root),
        "totals": {
            "all": len(records),
            "tracked_changed": tracked,
            "untracked": len(records) - tracked,
            "unknown": unknown,
        },
        "class_counts": counts,
        "class_labels": CLASS_LABELS,
        "warnings": warnings,
        "entries": entries,
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", default=str(DEFAULT_OUT))
    parser.add_argument("--strict", action="store_true", help="exit 1 while class I remains")
    args = parser.parse_args(argv)

    report = build_report()
    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    tmp = out.with_name(out.name + f".tmp{os.getpid()}")
    tmp.write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8")
    os.replace(tmp, out)

    totals = report["totals"]
    print(
        f"tree inventory: {totals['all']} paths "
        f"({totals['tracked_changed']} tracked changes, {totals['untracked']} untracked)"
    )
    for letter in sorted(CLASS_LABELS):
        print(f"  {letter} {CLASS_LABELS[letter]:45s} {report['class_counts'][letter]}")
    shown = report["warnings"][:40]
    for warning in shown:
        print(f"  WARN {warning}")
    hidden = len(report["warnings"]) - len(shown)
    if hidden > 0:
        print(f"  WARN ... and {hidden} more release-critical untracked paths (full list in JSON)")
    print(f"report: {out}")
    return 1 if args.strict and totals["unknown"] else 0


if __name__ == "__main__":
    sys.exit(main())
